### ISSUE TITLE
Unable to run illumina pipeline in Docker (ubuntu 20.04)

### ISSUE THREAD

**Issue by jwin4740** [onecodex/sars-cov-2#58]
STACK TRACE
`ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['jupyter', 'nbconvert', '--execute', '--to', 'onecodex_pdf', '--ExecutePreprocessor.timeout=-1', '--output=report.pdf', '--output-dir=.', 'report.ipynb']' command failed.  (See above for error)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/usr/local/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/usr/local/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
`

**Comment by audy** [comment]
@jwin4740 closing. If you are still running into this in the current release let me know.
